FROM debian-cdev

RUN apt-get update -qy && \
    apt-get install -qy libopencv-dev=4.5.1+dfsg-5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./opencv-cdev/example /examples/opencv-app

WORKDIR /app

CMD ["bash"]