# bullseye
FROM rapee9999/debian:11.7

RUN apt-get update -qy && \
    apt-get install -qy \
        libboost-dev=1.74.0.3 \
        g++=4:10.2.1-1 \
        cmake=3.18.4-2+deb11u1 \
        vim=2:8.2.2434-3+deb11u1 \
        wget=1.21-1+deb11u1 \
        curl=7.74.0-1.3+deb11u7 \
        zip=3.0-12 \
        psutils=1.17.dfsg-4 \
        pciutils=1:3.7.0-5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["bash"]