FROM rapee9999/libtorch-cdev:latest AS libtorch-stage

FROM rapee9999/tesseract-cdev:latest

COPY --from=libtorch-stage /opt /opt
COPY --from=libtorch-stage /examples /examples

ENV TORCH_DIR=/opt/libtorch/share/cmake

WORKDIR /app

CMD ["bash"]