FROM rapee9999/debian-cdev:latest AS download-stage

WORKDIR /opt

RUN wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip && \
    unzip "libtorch-cxx11-abi-shared-with-deps-2.0.1+cpu.zip"


FROM rapee9999/debian-cdev:latest

COPY --from=download-stage /opt/libtorch /opt/libtorch
COPY ./libtorch-cdev/example /examples/libtorch-app

ENV TORCH_DIR=/opt/libtorch/share/cmake

WORKDIR /app

CMD ["bash"]