FROM rapee9999/cv-cdev:latest

RUN apt-get update -y && \
    apt-get install -y python3 python3-dev python3-pip python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["bash"]
